### ISSUE TITLE
NullPointer error

### ISSUE THREAD

**Issue by MThomas564** [lamarios/Homedash2#7] opened 2019-01-19 10:01 UTC
I am getting a Java.lang.nullpointer when the application is running and I attempt to browse to the site. It is running on Windows10, not in docker. Any ideas?

**Comment by lamarios** [comment] 2019-01-19 10:09
Can you give me the command you’re using to run the application and the full error log otherwise there’s not much I can do.

**Comment by MThomas564** [comment] 2019-01-19 12:45
I am using the following command in the /web/target folder
java -Dconfig.file=./homedash.properties -jar Homedash-{version}.jar

The full error is as follows: 

[main] INFO org.quartz.core.QuartzScheduler - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
00:23:38.718 [qtp161827001-22] INFO  com.ftpix.homedash.app.App - GET -> http://localhost:4567/
00:23:38.725 [qtp161827001-22] INFO  com.ftpix.homedash.app.Endpoints - Finding all distinct plugins to load distinct JS files and CSS
00:23:38.728 [qtp161827001-22] INFO  com.ftpix.homedash.app.Endpoints - 0 plugins, 0 distinct plugins
[qtp161827001-22] ERROR spark.http.matching.GeneralError -
java.lang.NullPointerException
        at java.base/java.io.Reader.<init>(Reader.java:167)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:97)
        at de.neuland.jade4j.template.ClasspathTemplateLoader.getReader(ClasspathTemplateLoader.java:24)
        at spark.template.jade.loader.SparkClasspathTemplateLoader.getReader(SparkClasspathTemplateLoader.java:48)
        at de.neuland.jade4j.lexer.Lexer.<init>(Lexer.java:48)
        at de.neuland.jade4j.parser.Parser.<init>(Parser.java:47)
        at de.neuland.jade4j.JadeConfiguration.createTemplate(JadeConfiguration.java:86)
        at de.neuland.jade4j.JadeConfiguration.getTemplate(JadeConfiguration.java:59)
        at com.ftpix.homedash.utils.HomeDashTemplateEngine.render(HomeDashTemplateEngine.java:54)
        at spark.TemplateViewRouteImpl$1.render(TemplateViewRouteImpl.java:61)
        at spark.TemplateViewRouteImpl$1.render(TemplateViewRouteImpl.java:58)
        at spark.TemplateViewRouteImpl.render(TemplateViewRouteImpl.java:86)
        at spark.http.matching.Routes.execute(Routes.java:63)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:503)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by lamarios** [comment] 2019-01-22 08:05
Ok, I manage to reproduce the issue but it’s only happening when running from the built jar file so it’s going to be quite difficult to debug.

It’ll take me some time.

**Comment by MThomas564** [comment] 2019-01-22 08:07
Thanks, do you have a recommendation for another way to run it? Ideally don't want to use docker as want the network stats

**Comment by MThomas564** [comment] 2019-01-22 08:12
Thank you, if it doesn't work then no worries. Thanks for looking into it

**Comment by lamarios** [comment] 2019-01-23 11:13
Ok. It should be fixed for now. Let me know if it does work.

**Comment by MThomas564** [comment] 2019-01-25 08:06
Just downloaded the new version and tried again...

08:04:01.820 [qtp1217129450-18] INFO  com.ftpix.homedash.app.App - GET -> http://localhost:4567/js/websocket.js
08:04:01.822 [qtp1217129450-18] ERROR com.ftpix.homedash.app.Endpoints - Error while getting resource
java.lang.NullPointerException
        at com.ftpix.homedash.app.Endpoints.getContent(Endpoints.java:163) ~[Homedash-2019.01.3.jar:2019.01.3]
        at com.ftpix.homedash.app.Endpoints.lambda$staticResources$3(Endpoints.java:127) ~[Homedash-2019.01.3.jar:2019.01.3]
        at spark.RouteImpl$1.handle(RouteImpl.java:72) [Homedash-2019.01.3.jar:2019.01.3]
        at spark.http.matching.Routes.execute(Routes.java:61) [Homedash-2019.01.3.jar:2019.01.3]
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134) [Homedash-2019.01.3.jar:2019.01.3]
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.server.Server.handle(Server.java:503) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [Homedash-2019.01.3.jar:2019.01.3]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [Homedash-2019.01.3.jar:2019.01.3]
        at java.base/java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by lamarios** [comment] 2019-01-28 04:00
I'm not able to reproduce this one, can you let me know this:

- Java version
- Downloaded from the release page or built yourself ?
- Command ran to start it ? Did you use the create-config command beforehand ?

**Closed** 2019-01-29 09:38 UTC
